from __future__ import annotations

import difflib
import fcntl
import json
import os
import shutil
import tempfile
import tomllib
import uuid
from contextlib import contextmanager
from dataclasses import dataclass, field
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from murlocs.errors import MurlocsError
from murlocs.layers import compose
from murlocs.lockfile import LOCK_PATH, render_lock, sha256_bytes, sha256_text
from murlocs.manifest import load_manifest, parse_manifest_data
from murlocs.model import LayerSource, Manifest
from murlocs.paths import relative_posix, repo_path
from murlocs.render import render_outputs
from murlocs.serialization import render_fragment_data, render_manifest_data
from murlocs.source_annotations import annotation_provenance_payload
from murlocs.stewards import (
    LEGACY_MARKER,
    TranslationFinding,
    is_layered_steward,
    render_legacy_layered_maps,
    render_legacy_steward_maps,
    translate_layered_stewards,
    translate_stewards_manifest,
)
from murlocs.verify import validate

MIGRATION_STATE = Path(".murlocs/migration.json")
BACKUP_ROOT = Path(".murlocs/backups")
SKIP_DIRS = {".git", ".venv", "node_modules", "dist", "build", "__pycache__"}


@dataclass(frozen=True)
class MigrationCandidate:
    manifest: dict[str, Any]
    manifest_toml: str
    protocol_text: str
    findings: tuple[TranslationFinding, ...]
    layered: bool = False
    layer_files: tuple[tuple[str, str], ...] = ()
    resolved_data: dict[str, Any] | None = None
    sources: tuple[LayerSource, ...] = ()
    scope_layers: dict[str, tuple[str, ...]] = field(default_factory=dict)
    overrides: tuple[Any, ...] = ()

    def to_manifest(self, root: Path) -> Manifest:
        if self.resolved_data is None:
            return parse_manifest_data(root, self.manifest)
        return parse_manifest_data(
            root,
            self.resolved_data,
            layered=True,
            sources=self.sources,
            scope_layers=self.scope_layers,
            overrides=self.overrides,
        )


def inventory_repository(root: Path) -> dict[str, Any]:
    instructions: list[dict[str, str]] = []
    for directory, names, files in os.walk(root):
        current = Path(directory)
        names[:] = sorted(
            name
            for name in names
            if name not in SKIP_DIRS
            and current / name != root / BACKUP_ROOT
            and not (current / name / ".git").exists()
        )
        for filename in sorted(files):
            path = Path(directory) / filename
            relative = relative_posix(root, path)
            if filename not in {"AGENTS.md", "CLAUDE.md"} and relative != (
                ".github/copilot-instructions.md"
            ):
                continue
            text = path.read_text(encoding="utf-8", errors="replace")
            generator = "user"
            if text.startswith(LEGACY_MARKER):
                generator = "stewards"
            elif text.startswith("<!-- Generated by Murlocs."):
                generator = "murlocs"
            instructions.append({"path": relative, "kind": filename, "generator": generator})

    legacy = root / ".stewards" / "manifest.toml"
    summary: dict[str, Any] | None = None
    untranslatable: list[dict[str, Any]] = []
    sidecars: list[dict[str, str]] = []
    if (root / ".stewards").is_dir():
        declared: set[str] = set()
        if legacy.is_file():
            try:
                data = tomllib.loads(legacy.read_text(encoding="utf-8"))
            except (tomllib.TOMLDecodeError, OSError, ValueError) as exc:
                untranslatable.append(
                    {
                        "level": "blocking",
                        "code": "unreadable-manifest",
                        "message": f"legacy manifest could not be parsed: {exc}",
                        "subjects": [],
                    }
                )
            else:
                if isinstance(data.get("layer"), list):
                    declared = {
                        str(decl.get("path", ""))
                        for decl in data["layer"]
                        if isinstance(decl, dict)
                    }
                try:
                    summary, blocking = _legacy_summary(root, data)
                    untranslatable.extend(blocking)
                except (MurlocsError, OSError, ValueError, KeyError, TypeError) as exc:
                    # A read-only survey degrades gracefully: it lists what it can and
                    # names what it cannot, but never aborts with nothing.
                    untranslatable.append(
                        {
                            "level": "blocking",
                            "code": "MURLOCS_INVENTORY",
                            "message": str(exc),
                            "subjects": [],
                        }
                    )
        sidecars = _steward_sidecars(root, declared)
    annotations: list[dict[str, object]] = []
    if (root / ".murlocs" / "manifest.toml").is_file():
        try:
            annotations = annotation_provenance_payload(load_manifest(root))
        except (MurlocsError, OSError, ValueError, TypeError, KeyError):
            # Inventory remains an orientation command when a candidate is invalid.
            # The check surface owns deterministic annotation diagnostics.
            annotations = []
    return {
        "root": str(root),
        "instructions": instructions,
        "legacy_stewards": summary,
        "sidecars": sidecars,
        "untranslatable": untranslatable,
        "murlocs": {
            "manifest": (root / ".murlocs" / "manifest.toml").is_file(),
            "lock": (root / LOCK_PATH).is_file(),
            "migration": (root / MIGRATION_STATE).is_file(),
        },
        "ownership_conflicts": [
            item["path"]
            for item in instructions
            if item["kind"] == "AGENTS.md" and item["generator"] != "murlocs"
        ],
        "annotations": annotations,
    }


def _legacy_summary(
    root: Path, data: dict[str, Any]
) -> tuple[dict[str, Any], list[dict[str, Any]]]:
    """Summarize a legacy manifest, counting what translates and naming what is lost."""
    if is_layered_steward(data):
        translated = translate_layered_stewards(data, _read_steward_layers(root, data))
        scopes = sum(
            1
            for layer in translated.layers
            for scope in layer.fragment.get("scopes", [])
            if not scope.get("override")
        )
        invariants = sum(
            1
            for layer in translated.layers
            for invariant in layer.fragment.get("invariants", [])
            if not invariant.get("override")
        )
        checks = sum(len(layer.fragment.get("checks", {})) for layer in translated.layers)
        summary = {
            "network": translated.manifest["network"],
            "scopes": scopes,
            "invariants": invariants,
            "checks": checks,
            "layered": True,
            "layers": [
                {"id": layer.id, "kind": layer.kind, "owners": list(layer.owners)}
                for layer in translated.layers
            ],
            "proof_debt": sum(
                len(finding.subjects) for finding in translated.findings if finding.level == "debt"
            ),
        }
    else:
        translated = translate_stewards_manifest(data)
        summary = {
            "network": translated.manifest["network"],
            "scopes": len(translated.manifest["scopes"]),
            "invariants": len(translated.manifest["invariants"]),
            "checks": len(translated.manifest["checks"]),
            "layered": False,
            "layers": [],
            "proof_debt": sum(
                len(finding.subjects) for finding in translated.findings if finding.level == "debt"
            ),
        }
    blocking = [_finding_dict(item) for item in translated.findings if item.level == "blocking"]
    return summary, blocking


def _steward_sidecars(root: Path, declared: set[str]) -> list[dict[str, str]]:
    """List legacy constructs beside manifest.toml that Murlocs does not model.

    Archetype templates, portability kits, and back-reference resolvers are out of
    scope for translation. Surfacing them keeps the exotic subsystems from being
    silently invisible to an operator surveying a repository.
    """
    stewards_dir = root / ".stewards"
    if not stewards_dir.is_dir():
        return []
    modeled = {".stewards/manifest.toml", ".stewards/PROTOCOL.md"} | declared
    sidecars: list[dict[str, str]] = []
    for path in sorted(stewards_dir.rglob("*")):
        if not path.is_file():
            continue
        relative = relative_posix(root, path)
        if relative in modeled:
            continue
        sidecars.append({"path": relative, "construct": _classify_sidecar(relative)})
    return sidecars


def _classify_sidecar(relative: str) -> str:
    name = relative.rsplit("/", 1)[-1]
    if "/archetypes/" in relative:
        return "archetype"
    if name == "kit.toml":
        return "portability-kit"
    if name == "refs.py":
        return "ref-resolver"
    if name.endswith(".py"):
        return "script"
    if name.endswith(".toml"):
        return "toml"
    if name.endswith(".md"):
        return "guidance-doc"
    return "other"


def _sidecar_finding(sidecars: list[dict[str, str]]) -> TranslationFinding | None:
    """Name every out-of-scope sidecar so the loss report never omits one silently."""
    if not sidecars:
        return None
    return TranslationFinding(
        level="info",
        code="out-of-scope-sidecar",
        message=(
            "legacy sidecar constructs are not modeled by Murlocs; they are reported "
            "as out of scope and left untranslated rather than silently ignored"
        ),
        subjects=tuple(f"{item['path']} ({item['construct']})" for item in sidecars),
    )


def _read_steward_manifest(root: Path) -> tuple[dict[str, Any], str]:
    manifest_path = root / ".stewards" / "manifest.toml"
    protocol_path = root / ".stewards" / "PROTOCOL.md"
    if not manifest_path.is_file():
        raise MurlocsError(f"legacy steward manifest not found: {manifest_path}")
    if not protocol_path.is_file():
        raise MurlocsError(f"legacy steward protocol not found: {protocol_path}")
    data = tomllib.loads(manifest_path.read_text(encoding="utf-8"))
    return data, protocol_path.read_text(encoding="utf-8")


def _read_steward_layers(root: Path, data: dict[str, Any]) -> list[dict[str, Any]]:
    layer_datas: list[dict[str, Any]] = []
    for index, decl in enumerate(data.get("layer", [])):
        if not isinstance(decl, dict) or "path" not in decl:
            raise MurlocsError(f"legacy steward layer[{index}] requires a path")
        layer_path = repo_path(root, str(decl["path"]), field=f"steward layer[{index}] path")
        if not layer_path.is_file():
            raise MurlocsError(f"legacy steward layer file not found: {decl['path']}")
        layer_datas.append(tomllib.loads(layer_path.read_text(encoding="utf-8")))
    return layer_datas


def candidate_from_stewards(root: Path) -> MigrationCandidate:
    data, protocol_text = _read_steward_manifest(root)
    if is_layered_steward(data):
        return _layered_candidate(root, data, protocol_text)
    translated = translate_stewards_manifest(data)
    translated.manifest["protocol"] = ".murlocs/PROTOCOL.md"
    findings = _with_sidecars(translated.findings, _steward_sidecars(root, set()))
    return MigrationCandidate(
        manifest=translated.manifest,
        manifest_toml=render_manifest_data(translated.manifest),
        protocol_text=protocol_text,
        findings=findings,
    )


def _layered_candidate(root: Path, data: dict[str, Any], protocol_text: str) -> MigrationCandidate:
    layer_datas = _read_steward_layers(root, data)
    translated = translate_layered_stewards(data, layer_datas)
    root_manifest = translated.manifest
    root_manifest["protocol"] = ".murlocs/PROTOCOL.md"

    sources = [
        LayerSource(
            id="manifest",
            kind="base",
            path=".murlocs/manifest.toml",
            sha256="",
            owners=tuple(root_manifest.get("owners", [])),
        )
    ]
    fragments: list[dict[str, Any]] = [root_manifest]
    layer_files: list[tuple[str, str]] = []
    for layer in translated.layers:
        sources.append(
            LayerSource(
                id=layer.id,
                kind=layer.kind,
                path=layer.murlocs_path,
                sha256="",
                owners=layer.owners,
            )
        )
        fragments.append(layer.fragment)
        layer_files.append((layer.murlocs_path, render_fragment_data(layer.fragment)))

    declared = {
        str(decl["path"])
        for decl in data.get("layer", [])
        if isinstance(decl, dict) and "path" in decl
    }
    findings = _with_sidecars(translated.findings, _steward_sidecars(root, declared))

    # Unsupported composition is reported as blocking loss; do not resolve it into a model.
    blocking = any(finding.level == "blocking" for finding in translated.findings)
    if blocking:
        return MigrationCandidate(
            manifest=root_manifest,
            manifest_toml=render_manifest_data(root_manifest),
            protocol_text=protocol_text,
            findings=findings,
            layered=True,
            layer_files=tuple(layer_files),
        )
    resolved = compose(root_manifest, sources, fragments)
    return MigrationCandidate(
        manifest=root_manifest,
        manifest_toml=render_manifest_data(root_manifest),
        protocol_text=protocol_text,
        findings=findings,
        layered=True,
        layer_files=tuple(layer_files),
        resolved_data=resolved.data,
        sources=resolved.sources,
        scope_layers=resolved.scope_layers,
        overrides=resolved.overrides,
    )


def write_candidate(root: Path, candidate: MigrationCandidate, output: str) -> list[str]:
    blocking = [item for item in candidate.findings if item.level == "blocking"]
    if blocking:
        joined = "; ".join(item.code for item in blocking)
        raise MurlocsError(f"refusing to write candidate with blocking loss: {joined}")
    target = repo_path(root, output, field="candidate output")
    if target.exists():
        raise MurlocsError(f"refusing to overwrite candidate output: {output}")
    canonical = target == root / ".murlocs" / "manifest.toml"
    protocol = root / ".murlocs" / "PROTOCOL.md"
    if canonical and protocol.exists():
        raise MurlocsError("refusing to overwrite existing .murlocs/PROTOCOL.md")
    layer_targets: list[tuple[Path, str]] = []
    if canonical:
        for relative, content in candidate.layer_files:
            layer_target = repo_path(root, relative, field="candidate layer output")
            if layer_target.exists():
                raise MurlocsError(f"refusing to overwrite candidate layer: {relative}")
            layer_targets.append((layer_target, content))
    written = [relative_posix(root, target)]
    _write_text_atomic(target, candidate.manifest_toml)
    try:
        if canonical:
            _write_text_atomic(protocol, candidate.protocol_text)
            written.append(".murlocs/PROTOCOL.md")
            for layer_target, content in layer_targets:
                _write_text_atomic(layer_target, content)
                written.append(relative_posix(root, layer_target))
    except BaseException:
        target.unlink(missing_ok=True)
        protocol.unlink(missing_ok=True)
        for layer_target, _ in layer_targets:
            layer_target.unlink(missing_ok=True)
        raise
    return written


def diff_stewards_candidate(root: Path) -> dict[str, Any]:
    candidate = candidate_from_stewards(root)
    manifest = candidate.to_manifest(root)
    expected = render_outputs(manifest)
    rendered: list[dict[str, Any]] = []
    for relative, content in sorted(expected.items()):
        path = repo_path(root, relative, field="candidate map")
        before = path.read_text(encoding="utf-8") if path.is_file() else ""
        status = "same" if before == content else ("changed" if path.exists() else "added")
        patch = "".join(
            difflib.unified_diff(
                before.splitlines(keepends=True),
                content.splitlines(keepends=True),
                fromfile=f"a/{relative}",
                tofile=f"b/{relative}",
            )
        )
        rendered.append({"path": relative, "status": status, "diff": patch})
    return {
        "semantic": {
            "network": manifest.network,
            "scopes": len(manifest.scopes),
            "invariants": len(manifest.invariants),
            "checks": len(manifest.checks),
            "layered": candidate.layered,
            "layers": len(candidate.layer_files),
            "findings": [_finding_dict(item) for item in candidate.findings],
        },
        "rendered": rendered,
    }


def adopt_manifest(root: Path, *, dry_run: bool = False) -> dict[str, Any]:
    with _migration_lock(root):
        return _adopt_manifest_locked(root, dry_run=dry_run)


def _adopt_manifest_locked(root: Path, *, dry_run: bool = False) -> dict[str, Any]:
    if _active_state(root) is not None:
        raise MurlocsError("an active migration already exists; rollback it first")
    manifest = load_manifest(root)
    blocking = [item for item in validate(manifest) if item.code not in {"drift", "lock"}]
    if blocking:
        raise MurlocsError(
            "candidate manifest is not adoptable: " + "; ".join(str(item) for item in blocking)
        )
    legacy_path = root / ".stewards" / "manifest.toml"
    if not legacy_path.is_file():
        raise MurlocsError("adoption requires the source .stewards/manifest.toml")
    legacy_data = tomllib.loads(legacy_path.read_text(encoding="utf-8"))
    if is_layered_steward(legacy_data):
        legacy_maps = render_legacy_layered_maps(
            legacy_data, _read_steward_layers(root, legacy_data)
        )
    else:
        legacy_maps = render_legacy_steward_maps(legacy_data)
    outputs = render_outputs(manifest)
    if set(outputs) != set(legacy_maps):
        missing = sorted(set(legacy_maps) - set(outputs))
        added = sorted(set(outputs) - set(legacy_maps))
        raise MurlocsError(
            f"candidate map set differs from legacy network; missing={missing}, added={added}"
        )
    originals: list[str] = []
    created: list[str] = []
    for relative in outputs:
        target = repo_path(root, relative, field="adopted map")
        if target.is_file():
            expected_legacy = legacy_maps.get(relative)
            if expected_legacy is None:
                raise MurlocsError(f"existing map is not owned by the legacy network: {relative}")
            if target.read_text(encoding="utf-8") != expected_legacy:
                raise MurlocsError(f"legacy generated map is modified or stale: {relative}")
            originals.append(relative)
        elif target.exists():
            raise MurlocsError(f"map target is not a file: {relative}")
        else:
            created.append(relative)
    if dry_run:
        return {"adopted": sorted(outputs), "originals": originals, "created": created}

    migration_id = datetime.now(UTC).strftime("%Y%m%dT%H%M%SZ") + "-" + uuid.uuid4().hex[:8]
    backup = root / BACKUP_ROOT / migration_id
    files_backup = backup / "files"
    try:
        for relative in originals:
            source = repo_path(root, relative, field="backup source")
            destination = files_backup / relative
            destination.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(source, destination)
        lock = root / LOCK_PATH
        lock_existed = lock.is_file()
        if lock_existed:
            destination = files_backup / LOCK_PATH
            destination.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(lock, destination)
        for relative in originals:
            source = repo_path(root, relative, field="backup source")
            backed = files_backup / relative
            if not backed.is_file():
                raise MurlocsError(f"backup incomplete: {relative}")
            if sha256_bytes(backed.read_bytes()) != sha256_bytes(source.read_bytes()):
                raise MurlocsError(f"backup verification failed: {relative}")
        if lock_existed:
            backed_lock = files_backup / LOCK_PATH
            if not backed_lock.is_file() or sha256_bytes(backed_lock.read_bytes()) != sha256_bytes(
                lock.read_bytes()
            ):
                raise MurlocsError("backup verification failed: .murlocs/lock.json")
    except BaseException:
        shutil.rmtree(backup, ignore_errors=True)
        raise
    state = {
        "version": 1,
        "id": migration_id,
        "status": "adopted",
        "backup": relative_posix(root, backup),
        "originals": originals,
        "created": created,
        "lock_existed": lock_existed,
        "adopted_sha256": {path: sha256_text(content) for path, content in outputs.items()},
    }
    try:
        for relative, content in outputs.items():
            _write_text_atomic(repo_path(root, relative, field="adopted map"), content)
        manifest_bytes = manifest.manifest_path.read_bytes()
        _write_text_atomic(lock, render_lock(manifest_bytes, outputs, manifest.sources))
        _write_json_atomic(root / MIGRATION_STATE, state)
        _write_json_atomic(backup / "state.json", state)
    except BaseException:
        _restore_adoption(root, state, verify_current=False)
        raise
    return state


def prune_legacy(root: Path, *, dry_run: bool = False) -> dict[str, Any]:
    with _migration_lock(root):
        return _prune_legacy_locked(root, dry_run=dry_run)


def _prune_legacy_locked(root: Path, *, dry_run: bool = False) -> dict[str, Any]:
    state = _require_state(root, {"adopted"})
    legacy = root / ".stewards"
    if not legacy.is_dir():
        raise MurlocsError("legacy .stewards directory does not exist")
    paths = sorted(relative_posix(root, path) for path in legacy.rglob("*") if path.is_file())
    if dry_run:
        return {"pruned": paths}
    backup = repo_path(root, state["backup"], field="migration backup")
    destination = backup / "pruned" / ".stewards"
    destination.parent.mkdir(parents=True, exist_ok=True)
    shutil.move(str(legacy), destination)
    try:
        state["status"] = "pruned"
        state["pruned"] = paths
        _write_json_atomic(root / MIGRATION_STATE, state)
        _write_json_atomic(backup / "state.json", state)
    except BaseException:
        shutil.move(str(destination), legacy)
        raise
    return state


def rollback_migration(root: Path, *, dry_run: bool = False) -> dict[str, Any]:
    with _migration_lock(root):
        return _rollback_migration_locked(root, dry_run=dry_run)


def _rollback_migration_locked(root: Path, *, dry_run: bool = False) -> dict[str, Any]:
    state = _require_state(root, {"adopted", "pruned"})
    if dry_run:
        return {
            "restore": state["originals"],
            "remove": state["created"],
            "restore_legacy": state["status"] == "pruned",
        }
    _restore_adoption(root, state, verify_current=True)
    state["status"] = "rolled_back"
    _write_json_atomic(root / MIGRATION_STATE, state)
    backup = repo_path(root, state["backup"], field="migration backup")
    _write_json_atomic(backup / "state.json", state)
    return state


def _restore_adoption(root: Path, state: dict[str, Any], *, verify_current: bool) -> None:
    backup = repo_path(root, state["backup"], field="migration backup")
    # Pre-flight: confirm the whole backup is intact before mutating anything.
    # Reading a missing backup file mid-loop would otherwise raise a raw
    # FileNotFoundError after some files were already restored, leaving the
    # working tree half-restored.
    if not backup.is_dir():
        raise MurlocsError(
            f"migration backup is missing; cannot restore: {relative_posix(root, backup)}"
        )
    required = [backup / "files" / relative for relative in state["originals"]]
    if state["lock_existed"]:
        required.append(backup / "files" / LOCK_PATH)
    missing = sorted(relative_posix(root, path) for path in required if not path.is_file())
    if missing:
        raise MurlocsError("migration backup is incomplete; cannot restore: " + ", ".join(missing))
    if verify_current:
        for relative, expected in state["adopted_sha256"].items():
            target = repo_path(root, relative, field="rollback map")
            if not target.is_file() or sha256_bytes(target.read_bytes()) != expected:
                raise MurlocsError(f"refusing rollback over modified adopted map: {relative}")
    for relative in state["originals"]:
        source = backup / "files" / relative
        _write_bytes_atomic(repo_path(root, relative, field="rollback map"), source.read_bytes())
    for relative in state["created"]:
        repo_path(root, relative, field="rollback map").unlink(missing_ok=True)
    lock = root / LOCK_PATH
    if state["lock_existed"]:
        source = backup / "files" / LOCK_PATH
        _write_bytes_atomic(lock, source.read_bytes())
    else:
        lock.unlink(missing_ok=True)
    pruned = backup / "pruned" / ".stewards"
    if state.get("status") == "pruned" and pruned.is_dir():
        if (root / ".stewards").exists():
            raise MurlocsError("refusing to restore .stewards over an existing path")
        shutil.move(str(pruned), root / ".stewards")


def _active_state(root: Path) -> dict[str, Any] | None:
    path = root / MIGRATION_STATE
    if not path.is_file():
        return None
    data = _read_state(path)
    return data if data.get("status") in {"adopted", "pruned"} else None


def _require_state(root: Path, statuses: set[str]) -> dict[str, Any]:
    path = root / MIGRATION_STATE
    if not path.is_file():
        raise MurlocsError("migration state does not exist")
    data = _read_state(path)
    if data.get("status") not in statuses:
        raise MurlocsError(f"migration state is {data.get('status')}, expected {sorted(statuses)}")
    return data


def _read_state(path: Path) -> dict[str, Any]:
    """Load migration state, surfacing corruption as a clean MurlocsError.

    A truncated or hand-edited ``migration.json`` otherwise raises a raw
    ``JSONDecodeError`` (or ``UnicodeDecodeError``) traceback from deep inside a
    migration command instead of a deterministic, user-facing failure.
    """
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, UnicodeDecodeError) as exc:
        raise MurlocsError(f"migration state is corrupt and cannot be parsed: {path.name}") from exc
    if not isinstance(data, dict):
        raise MurlocsError(f"migration state is not a JSON object: {path.name}")
    return data


def _with_sidecars(
    findings: tuple[TranslationFinding, ...], sidecars: list[dict[str, str]]
) -> tuple[TranslationFinding, ...]:
    """Append the out-of-scope sidecar finding so import never omits one silently."""
    sidecar = _sidecar_finding(sidecars)
    if sidecar is None:
        return findings
    return (*findings, sidecar)


def _finding_dict(finding: TranslationFinding) -> dict[str, Any]:
    return {
        "level": finding.level,
        "code": finding.code,
        "message": finding.message,
        "subjects": list(finding.subjects),
    }


def _write_json_atomic(path: Path, data: dict[str, Any]) -> None:
    _write_text_atomic(path, json.dumps(data, indent=2, sort_keys=True) + "\n")


def _write_text_atomic(path: Path, content: str) -> None:
    _write_bytes_atomic(path, content.encode())


def _write_bytes_atomic(path: Path, content: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(descriptor, "wb") as handle:
            handle.write(content)
        os.replace(temporary, path)
    except BaseException:
        Path(temporary).unlink(missing_ok=True)
        raise


@contextmanager
def _migration_lock(root: Path):
    lock_path = root / ".murlocs" / "migration.lock"
    lock_path.parent.mkdir(parents=True, exist_ok=True)
    handle = lock_path.open("a+")
    try:
        fcntl.flock(handle.fileno(), fcntl.LOCK_EX | fcntl.LOCK_NB)
    except BlockingIOError as exc:
        handle.close()
        raise MurlocsError("another migration operation is in progress") from exc
    try:
        yield
    finally:
        fcntl.flock(handle.fileno(), fcntl.LOCK_UN)
        handle.close()
        lock_path.unlink(missing_ok=True)
