from __future__ import annotations

import os
import tempfile
from pathlib import Path

from murlocs.curation_transaction import transaction_pending
from murlocs.errors import MurlocsError
from murlocs.lockfile import LOCK_PATH, read_lock, render_lock, sha256_bytes
from murlocs.model import Check, Invariant, Manifest, Ownership, Scope
from murlocs.paths import repo_path

MARKER = "<!-- Generated by Murlocs. Edit .murlocs/manifest.toml, then run `murlocs compile`. -->"


def render_outputs(manifest: Manifest) -> dict[str, str]:
    return {scope.map: render_scope(manifest, scope) for scope in manifest.scopes}


def render_scope(manifest: Manifest, scope: Scope) -> str:
    invariants = [item for item in manifest.invariants if item.scope == scope.id]
    lines = [MARKER, "", f"# {manifest.network}: {scope.id}", "", scope.point_of_view, ""]
    if scope.id == "root":
        lines.extend(
            [
                "Ordinary work: use this root map plus only scoped maps on the target path.",
                f"Do not open `{manifest.protocol}` or `.murlocs/manifest.toml` unless the task "
                "is an explicit review, audit, or guidance-network change.",
                "",
            ]
        )
        _section(lines, "Pillars", manifest.pillars)
        _section(lines, "Search discipline", manifest.search_policy)
        _section(lines, "Operating rules", manifest.operating_rules)
        _network(lines, manifest)
    else:
        lines.extend(
            [
                "Ordinary work: use this map directly with the root map and only other maps "
                "whose scopes the task crosses.",
                f"Do not open `{manifest.protocol}` or `.murlocs/manifest.toml` unless the task "
                "is an explicit review, audit, or guidance-network change.",
                "",
            ]
        )
    _ownership(lines, scope.owns)
    _section(lines, "Guardrails", scope.guardrails)
    if invariants:
        lines.extend(["## Invariants", ""])
        for invariant in invariants:
            proof = _proof(invariant, manifest.checks)
            lines.append(
                f"- **{invariant.id}** ({invariant.severity}): {invariant.statement} {proof}"
            )
        lines.append("")
    if scope.edges:
        lines.extend(["## Edges", ""])
        for edge in scope.edges:
            lines.append(f"- `{edge.type}` → `{edge.to}`: {edge.what}")
        lines.append("")
    _section(lines, "Advocate", scope.judgment.advocate)
    _section(lines, "Do not", scope.judgment.do_not)
    _section(lines, "Serves", scope.judgment.serves)
    if scope.id == "root":
        if manifest.checks:
            lines.extend(["## Registered checks", ""])
            for name, check in sorted(manifest.checks.items()):
                description = f" — {check.description}" if check.description else ""
                lines.append(f"- `{name}`: `{check.invoke}`{description}")
            lines.append("")
        _section(lines, "Stop and ask", manifest.stop_and_ask)
        _section(lines, "Done means", manifest.done_criteria)
        lines.extend(
            [
                "## Review protocol",
                "",
                f"See [`{manifest.protocol}`]({manifest.protocol}) for cross-scope "
                "and critical changes.",
                "",
            ]
        )
    _provenance(lines, manifest, scope)
    return "\n".join(lines).rstrip() + "\n"


def _provenance(lines: list[str], manifest: Manifest, scope: Scope) -> None:
    """Name the ordered source layers and owners that contributed to this map."""
    if not manifest.layered:
        return
    layer_ids = manifest.source_ids_for_scope(scope.id)
    contributing = [manifest.source(layer_id) for layer_id in layer_ids]
    contributing = [source for source in contributing if source is not None]
    if not contributing:
        return
    lines.extend(
        [
            "## Provenance",
            "",
            "Edit the source layer below, then run `murlocs compile`. "
            "Do not edit this generated map.",
            "",
        ]
    )
    for source in contributing:
        owners = ", ".join(source.owners) if source.owners else "unowned"
        lines.append(f"- `{source.id}` ({source.kind}) — `{source.path}` · owners: {owners}")
    lines.append("")


def _section(lines: list[str], title: str, values: tuple[str, ...]) -> None:
    if not values:
        return
    lines.extend([f"## {title}", ""])
    lines.extend(f"- {value}" for value in values)
    lines.append("")


def _ownership(lines: list[str], ownership: Ownership) -> None:
    if not ownership.paths and not ownership.groups:
        return
    lines.extend(["## Owns", ""])
    lines.extend(f"- {path}" for path in ownership.paths)
    for group in ownership.groups:
        paths = ", ".join(f"`{path}`" for path in group.paths)
        lines.append(f"- **{group.kind}:** {paths}")
    lines.append("")


def _network(lines: list[str], manifest: Manifest) -> None:
    grouped = {
        scope.id: [item for item in manifest.invariants if item.scope == scope.id]
        for scope in manifest.scopes
    }
    lines.extend(
        [
            "## Network",
            "",
            "| Scope | Map | Invariants | Command-backed |",
            "| --- | --- | ---: | ---: |",
        ]
    )
    for scope in sorted(manifest.scopes, key=lambda item: item.id):
        invariants = grouped[scope.id]
        commands = sum(item.verification == "command" for item in invariants)
        ratio = f"{100 * commands // len(invariants)}%" if invariants else "—"
        lines.append(f"| {scope.id} | `{scope.map}` | {len(invariants)} | {ratio} |")
    lines.append("")


def _proof(invariant: Invariant, checks: dict[str, Check]) -> str:
    if invariant.verification == "command":
        check = checks.get(invariant.enforced_by or "")
        if check is not None:
            return f"Verify with `{check.invoke}` (`{check.name}`)."
        return f"Verify with `{invariant.enforced_by}`."
    if invariant.verification == "manual":
        return f"Evidence: `{invariant.evidence_file}` contains `{invariant.anchor}`."
    return "Verification is currently unknown; treat this as declared debt."


def prepare_manifest(manifest: Manifest) -> dict[str, str]:
    """Render and preflight every output without writing files."""
    if transaction_pending(manifest.root):
        raise MurlocsError(
            "an interrupted curation transaction must be recovered before compilation"
        )
    outputs = render_outputs(manifest)
    lock = read_lock(manifest.root)
    expected = set(outputs)
    if lock:
        orphaned = sorted(set(lock.generated) - expected)
        if orphaned:
            joined = ", ".join(orphaned)
            raise MurlocsError(
                f"lockfile owns maps no longer declared: {joined}; remove them explicitly"
            )

    for relative in outputs:
        target = repo_path(manifest.root, relative, field="scopes[].map")
        if target.exists():
            if lock is None or relative not in lock.generated:
                raise MurlocsError(f"refusing to overwrite unmanaged file: {relative}")
            actual = sha256_bytes(target.read_bytes())
            if actual != lock.generated[relative]:
                raise MurlocsError(f"refusing to overwrite modified generated file: {relative}")
    return outputs


def compile_manifest(manifest: Manifest) -> list[str]:
    outputs = prepare_manifest(manifest)
    for relative, content in outputs.items():
        target = repo_path(manifest.root, relative, field="scopes[].map")
        _atomic_write(target, content)
    manifest_bytes = manifest.manifest_path.read_bytes()
    _atomic_write(
        manifest.root / LOCK_PATH,
        render_lock(manifest_bytes, outputs, manifest.sources),
    )
    return sorted(outputs)


def _atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(content)
        os.replace(temporary, path)
    except BaseException:
        Path(temporary).unlink(missing_ok=True)
        raise
