from __future__ import annotations

# The legacy-map fixture preserves exact generated bytes, including long Markdown lines.
# ruff: noqa: E501
import json
import os
import subprocess
import sys
from pathlib import Path

import pytest


def active_environment_scripts() -> tuple[Path, Path]:
    """Return the package executables adjacent to pytest's active interpreter."""
    python = Path(sys.executable)
    return python.with_name("murlocs"), python


MURLOCS, PACKAGE_PYTHON = active_environment_scripts()
JOURNEY_DOC = Path(__file__).parents[1] / "docs" / "journeys.md"
PROJECT_SRC = Path(__file__).parents[1] / "src"

LEGACY_MANIFEST = """\
network = "Example"
protocol = ".stewards/PROTOCOL.md"
max_active_bytes = 24576
coverage_roots = []
pillars = ["Repository guidance is reviewed."]
search_policy = []
operating_rules = []
stop_and_ask = []
done_criteria = []

[check.contract]
invoke = "python -m pytest tests/test_contract.py -q"
location = "tests/test_contract.py"

[[steward]]
id = "root"
path = "AGENTS.md"
point_of_view = "Repository-wide contracts."

[[invariant]]
id = "contract"
steward = "root"
statement = "The public contract remains tested."
severity = "P1"
verification = "machine"
enforced_by = "contract"
"""

LEGACY_ROOT_MAP = """\
<!-- generated from .stewards/manifest.toml — edit the manifest, not this file -->

# Agent Constitution — Example

Ordinary work: use this root map plus only scoped maps on the target path.
Do not open `.stewards/PROTOCOL.md` or `.stewards/manifest.toml` unless the task is an explicit review/audit or steward-network maintenance.

## Pillars

- Repository guidance is reviewed.

## Network

| Steward | Map | Invariants | Automated backing |
| --- | --- | --- | --- |
| root | `AGENTS.md` | 1 | 100% |

## Protects (constitution)

| Invariant | Sev | Backing | Proof / anchor |
| --- | --- | --- | --- |
| The public contract remains tested. | P1 | machine-backed | `python -m pytest tests/test_contract.py -q` (`contract`) |

---

Explicit review/audit only: [.stewards/PROTOCOL.md](.stewards/PROTOCOL.md). Steward maintenance only: [.stewards/manifest.toml](.stewards/manifest.toml), then `python .stewards/verify.py --coverage`.
"""


def run(
    argv: list[str],
    *,
    cwd: Path,
    expected: int = 0,
) -> subprocess.CompletedProcess[str]:
    result = subprocess.run(
        argv,
        cwd=cwd,
        env={
            **os.environ,
            "NO_COLOR": "1",
            "PYTHONPATH": os.pathsep.join(
                value
                for value in (str(PROJECT_SRC), os.environ.get("PYTHONPATH"))
                if value
            ),
        },
        text=True,
        capture_output=True,
        check=False,
    )
    assert result.returncode == expected, (
        f"expected exit {expected}, got {result.returncode}: {' '.join(argv)}\n"
        f"stdout:\n{result.stdout}\nstderr:\n{result.stderr}"
    )
    return result


def murlocs(root: Path, *args: str, expected: int = 0) -> subprocess.CompletedProcess[str]:
    assert MURLOCS.is_file(), "acceptance tests require the installed console script"
    return run([str(MURLOCS), *args, "--repo", str(root)], cwd=root, expected=expected)


def git(root: Path, *args: str) -> str:
    return run(["git", *args], cwd=root).stdout.strip()


def initialize_git(root: Path) -> None:
    root.mkdir(parents=True, exist_ok=True)
    git(root, "init", "--quiet")
    git(root, "config", "user.name", "Murlocs Acceptance")
    git(root, "config", "user.email", "acceptance@example.invalid")
    git(root, "config", "commit.gpgsign", "false")


def commit_all(root: Path, message: str) -> None:
    git(root, "add", ".")
    git(root, "commit", "--quiet", "-m", message)


def test_disposable_repository_does_not_inherit_commit_signing(
    tmp_path: Path, monkeypatch
) -> None:
    inherited = write(tmp_path, "global.gitconfig", "[commit]\n\tgpgsign = true\n")
    monkeypatch.setenv("GIT_CONFIG_GLOBAL", str(inherited))
    root = tmp_path / "repository"

    initialize_git(root)
    write(root, "README.md", "# Test repository\n")
    commit_all(root, "unsigned fixture commit")

    assert git(root, "config", "--local", "--get", "commit.gpgsign") == "false"
    assert git(root, "log", "-1", "--format=%an <%ae>") == (
        "Murlocs Acceptance <acceptance@example.invalid>"
    )


def test_console_scripts_ignore_conflicting_path_entry(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    unrelated_bin = tmp_path / "unrelated-bin"
    unrelated_bin.mkdir()
    unrelated_murlocs = write(unrelated_bin, "murlocs", "#!/bin/sh\n")
    monkeypatch.setenv("PATH", str(unrelated_bin))

    murlocs_script, package_python = active_environment_scripts()

    assert murlocs_script == Path(sys.executable).with_name("murlocs")
    assert package_python == Path(sys.executable)
    assert murlocs_script != unrelated_murlocs


def repository_bytes(root: Path) -> dict[str, bytes]:
    return {
        path.relative_to(root).as_posix(): path.read_bytes()
        for path in sorted(root.rglob("*"))
        if path.is_file() and ".git" not in path.relative_to(root).parts
    }


def assert_unchanged(root: Path, before: dict[str, bytes], status: str) -> None:
    assert repository_bytes(root) == before
    assert git(root, "status", "--short") == status


def snapshot(root: Path) -> tuple[dict[str, bytes], str]:
    return repository_bytes(root), git(root, "status", "--short")


def write(root: Path, relative: str, content: str) -> Path:
    path = root / relative
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return path


def enable_ownership_policy(root: Path) -> None:
    manifest = root / ".murlocs" / "manifest.toml"
    text = manifest.read_text(encoding="utf-8")
    manifest.write_text(
        text.replace(
            "max_active_bytes = 24576",
            'max_active_bytes = 24576\nowners = ["@platform"]',
        ).replace(
            "[policies]\nrequire_scope_invariants = false",
            "[policies]\nrequire_scope_invariants = false\n"
            "require_layer_owners = true\nvalidate_codeowners = true",
        ),
        encoding="utf-8",
    )


def test_greenfield_bootstrap_with_explicit_coverage(tmp_path: Path) -> None:
    root = tmp_path / "greenfield"
    write(root, "src/app/core.py", "VALUE = 1\n")
    initialize_git(root)
    commit_all(root, "initial source")

    before, status = snapshot(root)
    preview = murlocs(
        root, "--dry-run", "init", "--name", "Example", "--coverage-root", "src"
    )
    assert "would write .murlocs/manifest.toml" in preview.stdout
    assert "coverage incomplete" in preview.stdout
    structured_preview = murlocs(
        root,
        "--dry-run",
        "init",
        "--name",
        "Example",
        "--coverage-root",
        "src",
        "--format",
        "json",
    )
    assert json.loads(structured_preview.stdout)["coverage"] == {
        "evaluated": True,
        "roots": ["src"],
        "state": "structurally_incomplete",
    }
    assert_unchanged(root, before, status)

    initialized = murlocs(
        root, "init", "--name", "Example", "--coverage-root", "src", "--format", "json"
    )
    assert json.loads(initialized.stdout)["generated"] == ["AGENTS.md"]
    murlocs(root, "add-scope", "src/app", "--owners", "@app")

    before, status = snapshot(root)
    compile_preview = murlocs(root, "--dry-run", "compile")
    assert "would write AGENTS.md" in compile_preview.stdout
    assert "would write src/app/AGENTS.md" in compile_preview.stdout
    assert_unchanged(root, before, status)

    murlocs(root, "compile")
    checked = murlocs(root, "check")
    assert "coverage structurally complete" in checked.stdout
    checked_json = json.loads(murlocs(root, "check", "--format", "json").stdout)
    assert checked_json["ok"] is True
    assert checked_json["coverage"]["state"] == "structurally_complete"

    explained = murlocs(root, "explain", "src/app/core.py")
    assert "[root] AGENTS.md" in explained.stdout
    assert "[src-app] src/app/AGENTS.md" in explained.stdout
    explained_json = json.loads(
        murlocs(root, "explain", "src/app/core.py", "--format", "json").stdout
    )
    assert [scope["id"] for scope in explained_json["scopes"]] == ["root", "src-app"]


def test_packaged_parser_preserves_repeated_bootstrap_and_rollout_values(
    tmp_path: Path,
) -> None:
    root = tmp_path / "repeatable-options"
    write(root, "src/app.py", "VALUE = 1\n")
    write(root, "tests/test_app.py", "def test_app(): pass\n")
    write(root, "docs/guide.md", "# Guide\n")
    write(root, "legacy/old.py", "OLD = 1\n")
    write(root, "examples/demo.py", "DEMO = 1\n")

    initialized = murlocs(
        root,
        "--dry-run",
        "init",
        "--coverage-root",
        "src",
        "--coverage-root",
        "tests",
        "--format",
        "json",
    )
    assert json.loads(initialized.stdout)["coverage"]["roots"] == ["src", "tests"]

    inline_empty = murlocs(
        root,
        "--dry-run",
        "init",
        "--coverage-root=",
        "--format",
        "json",
        expected=2,
    )
    assert "argument --coverage-root: expected at least one argument" in inline_empty.stderr

    murlocs(root, "init")
    rollout = murlocs(
        root,
        "--dry-run",
        "add-scope",
        "docs",
        "--owners",
        "@docs",
        "--owners",
        "@reviewers",
        "--defer",
        "legacy=migrating later",
        "--defer",
        "examples=adopting later",
        "--format",
        "json",
    )
    payload = json.loads(rollout.stdout)
    assert payload["owners"] == ["@docs", "@reviewers"]
    assert payload["deferred"] == {
        "examples": "adopting later",
        "legacy": "migrating later",
    }
    assert not (root / ".murlocs" / "layers").exists()


def test_packaged_parser_preserves_inline_dash_path(tmp_path: Path) -> None:
    root = tmp_path / "dash-path"
    write(root, "-dash.py", "VALUE = 1\n")
    murlocs(root, "init")

    impacted = murlocs(root, "impact", "--path=-dash.py", "--format", "json")

    assert json.loads(impacted.stdout)["input"]["paths"] == ["-dash.py"]


def test_progressive_owned_rollout_with_deferral_and_codeowners(tmp_path: Path) -> None:
    root = tmp_path / "rollout"
    write(root, "src/app/core.py", "VALUE = 1\n")
    write(root, "src/app/api/handler.py", "def handle(): return None\n")
    write(root, "legacy/old.py", "OLD = True\n")
    initialize_git(root)
    murlocs(root, "init", "--coverage-root", "src", "--coverage-root", "legacy")
    enable_ownership_policy(root)
    write(root, ".github/CODEOWNERS", "")
    commit_all(root, "root guidance")

    before, status = snapshot(root)
    preview = murlocs(
        root,
        "--dry-run",
        "add-scope",
        "src/app",
        "--owners",
        "@app",
        "--defer",
        "legacy=migrating later",
        "--format",
        "json",
    )
    payload = json.loads(preview.stdout)
    assert payload["deferred"] == {"legacy": "migrating later"}
    app_requirement = next(
        item
        for item in payload["codeowners_requirements"]
        if item["path"] == ".murlocs/layers/src-app.toml"
    )
    assert app_requirement["entry"] == "/.murlocs/layers/src-app.toml @app"
    assert app_requirement["blocking"] is True
    assert_unchanged(root, before, status)

    rejected = murlocs(
        root,
        "add-scope",
        "src/app",
        "--owners",
        "@app",
        "--defer",
        "legacy=migrating later",
        expected=1,
    )
    assert "exact entries before applying" in rejected.stderr
    assert_unchanged(root, before, status)

    codeowners = root / ".github" / "CODEOWNERS"
    codeowners.write_text(
        "/.murlocs/manifest.toml @platform\n"
        "/.murlocs/layers/src-app.toml @app\n",
        encoding="utf-8",
    )
    commit_all(root, "approve app layer")
    murlocs(
        root,
        "add-scope",
        "src/app",
        "--owners",
        "@app",
        "--defer",
        "legacy=migrating later",
    )

    before, status = snapshot(root)
    nested_preview = murlocs(
        root,
        "--dry-run",
        "add-scope",
        "src/app/api",
        "--owners",
        "@api",
        "--format",
        "json",
    )
    nested_requirements = json.loads(nested_preview.stdout)["codeowners_requirements"]
    nested_requirement = next(
        item
        for item in nested_requirements
        if item["path"] == ".murlocs/layers/src-app-api.toml"
    )
    assert nested_requirement["entry"] == "/.murlocs/layers/src-app-api.toml @api"
    assert_unchanged(root, before, status)
    codeowners.write_text(
        codeowners.read_text(encoding="utf-8")
        + "/.murlocs/layers/src-app-api.toml @api\n",
        encoding="utf-8",
    )
    murlocs(root, "add-scope", "src/app/api", "--owners", "@api")

    assert "migrating later" in (root / ".murlocs/layers/src-app.toml").read_text()
    assert "coverage structurally complete" in murlocs(root, "check").stdout
    chain = json.loads(
        murlocs(root, "explain", "src/app/api/handler.py", "--format", "json").stdout
    )
    assert [scope["id"] for scope in chain["scopes"]] == [
        "root",
        "src-app",
        "src-app-api",
    ]


def make_legacy_repo(root: Path) -> None:
    write(root, ".stewards/manifest.toml", LEGACY_MANIFEST)
    write(root, ".stewards/PROTOCOL.md", "# Review protocol\n")
    write(root, "AGENTS.md", LEGACY_ROOT_MAP)
    write(root, "src/app.py", "VALUE = 1\n")
    write(root, "tests/test_contract.py", "def test_contract(): pass\n")
    initialize_git(root)
    commit_all(root, "legacy guidance")


def test_legacy_migration_backup_prune_and_rollback_contract(tmp_path: Path) -> None:
    root = tmp_path / "migration"
    make_legacy_repo(root)
    legacy_bytes = (root / "AGENTS.md").read_bytes()

    inventory = murlocs(root, "inventory")
    assert "legacy network: 1 scope(s), 1 invariant(s), 1 check(s)" in inventory.stdout
    inventory_json = json.loads(murlocs(root, "inventory", "--format", "json").stdout)
    assert inventory_json["legacy_stewards"]["proof_debt"] == 1
    semantic = json.loads(
        murlocs(root, "diff", "--mode", "semantic", "--format", "json").stdout
    )
    assert semantic["semantic"]["findings"][0]["code"] == "missing-proof-anchor"
    assert "--- a/AGENTS.md" in murlocs(root, "diff", "--mode", "rendered").stdout

    before, status = snapshot(root)
    import_preview = murlocs(
        root,
        "--dry-run",
        "import",
        "--from",
        "stewards",
        "--output",
        ".murlocs/manifest.toml",
    )
    assert "would write .murlocs/manifest.toml" in import_preview.stdout
    assert_unchanged(root, before, status)

    imported = murlocs(
        root,
        "import",
        "--from",
        "stewards",
        "--output",
        ".murlocs/manifest.toml",
        "--format",
        "json",
    )
    assert json.loads(imported.stdout)["findings"][0]["level"] == "debt"
    blocked = murlocs(root, "check", expected=1)
    assert "proof-debt" in blocked.stderr
    candidate = root / ".murlocs/manifest.toml"
    candidate.write_text(
        candidate.read_text(encoding="utf-8").replace(
            'location = "tests/test_contract.py"',
            'location = "tests/test_contract.py"\nproof_contains = "test_contract"',
        ),
        encoding="utf-8",
    )
    resolved = murlocs(root, "check", expected=1)
    assert "lockfile is missing" in resolved.stderr
    assert "proof-debt" not in resolved.stderr

    before, status = snapshot(root)
    adopt_preview = json.loads(
        murlocs(root, "--dry-run", "adopt", "--format", "json").stdout
    )
    assert adopt_preview["adopted"] == ["AGENTS.md"]
    assert_unchanged(root, before, status)

    adopted = json.loads(murlocs(root, "adopt", "--format", "json").stdout)
    backup = root / adopted["backup"]
    assert (backup / "files/AGENTS.md").read_bytes() == legacy_bytes
    adopted_bytes = (root / "AGENTS.md").read_bytes()
    assert adopted_bytes != legacy_bytes
    assert json.loads(murlocs(root, "check", "--format", "json").stdout)["ok"] is True
    assert "[root] AGENTS.md" in murlocs(root, "explain", "src/app.py").stdout

    (root / "AGENTS.md").write_text("post-adoption edit\n", encoding="utf-8")
    before, status = snapshot(root)
    refused = murlocs(root, "rollback", expected=1)
    assert "modified adopted map" in refused.stderr
    assert_unchanged(root, before, status)
    (root / "AGENTS.md").write_bytes(adopted_bytes)

    before, status = snapshot(root)
    prune_preview = murlocs(root, "--dry-run", "prune")
    rollback_preview = json.loads(
        murlocs(root, "--dry-run", "rollback", "--format", "json").stdout
    )
    assert "would prune" in prune_preview.stdout
    assert rollback_preview["restore"] == ["AGENTS.md"]
    assert rollback_preview["restore_legacy"] is False
    assert_unchanged(root, before, status)

    murlocs(root, "prune")
    assert not (root / ".stewards").exists()
    assert (backup / "pruned/.stewards/manifest.toml").is_file()
    before, status = snapshot(root)
    rollback_after_prune = json.loads(
        murlocs(root, "--dry-run", "rollback", "--format", "json").stdout
    )
    assert rollback_after_prune["restore_legacy"] is True
    assert_unchanged(root, before, status)
    murlocs(root, "rollback")
    assert (root / "AGENTS.md").read_bytes() == legacy_bytes
    assert (root / ".stewards/manifest.toml").read_text() == LEGACY_MANIFEST
    assert not (root / ".murlocs/lock.json").exists()
    state = json.loads((root / ".murlocs/migration.json").read_text())
    assert state["status"] == "rolled_back"


def test_ordinary_layer_and_output_drift_repair(tmp_path: Path) -> None:
    root = tmp_path / "maintenance"
    write(root, "docs/guide.md", "# Guide\n")
    initialize_git(root)
    murlocs(root, "init")
    murlocs(root, "add-scope", "docs", "--owners", "@docs")
    commit_all(root, "managed guidance")

    layer = root / ".murlocs/layers/docs.toml"
    layer.write_text(
        layer.read_text(encoding="utf-8").replace(
            'point_of_view = "Guidance for docs."',
            'point_of_view = "Reviewed documentation guidance."',
        ),
        encoding="utf-8",
    )
    drift = murlocs(root, "check", expected=1)
    assert "layer changed since the last compile" in drift.stderr
    drift_result = murlocs(root, "check", "--format", "json", expected=1)
    assert drift_result.stderr == ""
    drift_json = json.loads(drift_result.stdout)
    assert drift_json["ok"] is False
    assert any(
        item["code"] == "drift" and "layer changed" in item["message"]
        for item in drift_json["findings"]
    )
    murlocs(root, "compile")
    assert "Reviewed documentation guidance." in (root / "docs/AGENTS.md").read_text()

    generated = root / "docs/AGENTS.md"
    compiled_bytes = generated.read_bytes()
    generated.write_text("manual edit\n", encoding="utf-8")
    before, status = snapshot(root)
    refused = murlocs(root, "compile", expected=1)
    assert "modified generated file" in refused.stderr
    assert_unchanged(root, before, status)

    generated.write_bytes(compiled_bytes)
    murlocs(root, "compile")
    assert json.loads(murlocs(root, "check", "--format", "json").stdout)["ok"] is True


def test_packaged_structured_failures_preserve_terminal_exit_codes(tmp_path: Path) -> None:
    root = tmp_path / "structured-failures"
    write(root, "src/app.py", "VALUE = 1\n")
    initialize_git(root)
    murlocs(root, "init")

    manifest = root / ".murlocs" / "manifest.toml"
    manifest.write_text(
        manifest.read_text(encoding="utf-8").replace(
            "Repository guidance", "Changed guidance"
        ),
        encoding="utf-8",
    )
    drift = murlocs(root, "check", "--format", "json", expected=1)
    assert drift.stderr == ""
    drift_payload = json.loads(drift.stdout)
    assert drift_payload["ok"] is False
    assert any(item["code"] == "drift" for item in drift_payload["findings"])

    curation = root / ".murlocs" / "curation"
    curation.mkdir()
    write(curation, "malformed.toml", "not valid toml = [\n")
    malformed = murlocs(root, "curate", "check", "--format", "json", expected=1)
    assert malformed.stderr == ""
    malformed_payload = json.loads(malformed.stdout)
    assert malformed_payload["ok"] is False
    assert malformed_payload["findings"]

    missing = murlocs(
        root, "curate", "review", "missing-proposal", "--format", "json", expected=1
    )
    assert missing.stderr == ""
    missing_payload = json.loads(missing.stdout)
    assert missing_payload["ok"] is False
    assert missing_payload["error"]["code"] == "MURLOCS_CURATE_REVIEW"

    absent = tmp_path / "absent-repository"
    invalid_root = run(
        [str(MURLOCS), "compile", "--repo", str(absent), "--format", "json"],
        cwd=tmp_path,
        expected=1,
    )
    assert invalid_root.stderr == ""
    invalid_payload = json.loads(invalid_root.stdout)
    assert invalid_payload["ok"] is False
    assert invalid_payload["error"]["code"] == "MURLOCS_COMPILE"


def test_recorded_evaluation_ingestion_is_reproducible_and_read_only(tmp_path: Path) -> None:
    root = tmp_path / "evaluation"
    initialize_git(root)
    task = write(
        root,
        "evaluation/task.toml",
        """\
schema_version = 1
id = "dependency-check"
prompt = "Which module does src/service.py use?"
target_path = "src/service.py"
repository_revision = "abc123"
correctness_threshold = 1.0

[[expected_facts]]
id = "uses-store"
description = "The service uses the store."
any_of = ["app.store", "store.py"]
""",
    )
    runs = {
        "schema_version": 1,
        "task_id": "dependency-check",
        "repository_revision": "abc123",
        "runs": [
            {
                "arm": arm,
                "model": "recorded-model",
                "ade": "recorded-agent",
                "guidance_revision": "none" if arm == "no-guidance" else f"{arm}-v1",
                "answer": "unknown" if arm == "no-guidance" else "Uses app.store.",
                "guidance_text": "" if arm == "no-guidance" else arm,
                "evidence": {
                    "files_inspected": count,
                    "lines_inspected": count * 10,
                    "tool_calls": count,
                    "executable_steps": count,
                    "transcript": [f"recorded {arm}"],
                },
            }
            for arm, count in (("no-guidance", 6), ("inline-dump", 4), ("murlocs", 2))
        ],
    }
    runs_path = write(root, "evaluation/runs.json", json.dumps(runs, indent=2) + "\n")
    commit_all(root, "recorded evaluation")
    before, status = snapshot(root)

    first = tmp_path / "results-one"
    scored = run(
        [
            str(PACKAGE_PYTHON),
            "-m",
            "murlocs.eval",
            "--task",
            str(task),
            "--runs",
            str(runs_path),
            "--output",
            str(first),
        ],
        cwd=root,
    )
    assert "no-guidance" in scored.stdout
    assert "below correctness threshold" in scored.stdout
    assert "most efficient correct arm: murlocs" in scored.stdout
    result = json.loads((first / "dependency-check.json").read_text())
    assert result["schema_version"] == 1
    assert result["summary"]["most_efficient_arm"] == "murlocs"
    assert result["summary"]["scores"][0]["efficiency"] is None

    second = tmp_path / "results-two"
    run(
        [
            str(PACKAGE_PYTHON),
            "-m",
            "murlocs.eval",
            "--task",
            str(task),
            "--runs",
            str(runs_path),
            "--output",
            str(second),
        ],
        cwd=root,
    )
    assert (first / "dependency-check.json").read_bytes() == (
        second / "dependency-check.json"
    ).read_bytes()
    assert_unchanged(root, before, status)

    invalid = dict(runs)
    invalid["repository_revision"] = "wrong"
    invalid_path = write(tmp_path, "invalid-runs.json", json.dumps(invalid))
    failed_output = tmp_path / "failed-results"
    before, status = snapshot(root)
    rejected = run(
        [
            str(PACKAGE_PYTHON),
            "-m",
            "murlocs.eval",
            "--task",
            str(task),
            "--runs",
            str(invalid_path),
            "--output",
            str(failed_output),
        ],
        cwd=root,
        expected=2,
    )
    assert "does not match task" in rejected.stderr
    assert not failed_output.exists()
    assert_unchanged(root, before, status)


@pytest.mark.parametrize(
    "command",
    [
        "murlocs init --coverage-root src",
        "murlocs --dry-run add-scope src/app --owners @app",
        "murlocs inventory",
        "murlocs diff --mode semantic",
        "murlocs import --from stewards --output .murlocs/manifest.toml",
        "murlocs --dry-run adopt",
        "murlocs prune",
        "murlocs rollback",
        "murlocs check --format json",
        "murlocs explain src/app/core.py --format json",
        "python -m murlocs.eval --task evaluation/task.toml --runs evaluation/runs.json",
    ],
)
def test_user_journey_recipes_stay_checked(command: str) -> None:
    assert command in JOURNEY_DOC.read_text(encoding="utf-8")
