from __future__ import annotations

import os
import tempfile
from pathlib import Path

from kodama.errors import KodamaError
from kodama.lockfile import LOCK_PATH, read_lock, render_lock, sha256_bytes
from kodama.model import Invariant, Manifest, Scope
from kodama.paths import repo_path

MARKER = "<!-- Generated by Kodama. Edit .kodama/manifest.toml, then run `kodama compile`. -->"


def render_outputs(manifest: Manifest) -> dict[str, str]:
    return {scope.map: render_scope(manifest, scope) for scope in manifest.scopes}


def render_scope(manifest: Manifest, scope: Scope) -> str:
    invariants = [item for item in manifest.invariants if item.scope == scope.id]
    lines = [MARKER, "", f"# {manifest.network}: {scope.id}", "", scope.point_of_view, ""]
    if scope.id == "root":
        _section(lines, "Pillars", manifest.pillars)
        _section(lines, "Operating rules", manifest.operating_rules)
    _section(lines, "Owns", scope.owns)
    _section(lines, "Guardrails", scope.guardrails)
    if invariants:
        lines.extend(["## Invariants", ""])
        for invariant in invariants:
            proof = _proof(invariant)
            lines.append(
                f"- **{invariant.id}** ({invariant.severity}): {invariant.statement} {proof}"
            )
        lines.append("")
    if scope.edges:
        lines.extend(["## Edges", ""])
        for edge in scope.edges:
            lines.append(f"- `{edge.type}` → `{edge.to}`: {edge.what}")
        lines.append("")
    if scope.id == "root":
        if manifest.checks:
            lines.extend(["## Registered checks", ""])
            for name, check in sorted(manifest.checks.items()):
                description = f" — {check.description}" if check.description else ""
                lines.append(f"- `{name}`: `{check.invoke}`{description}")
            lines.append("")
        _section(lines, "Stop and ask", manifest.stop_and_ask)
        _section(lines, "Done means", manifest.done_criteria)
        lines.extend(
            [
                "## Review protocol",
                "",
                f"See [`{manifest.protocol}`]({manifest.protocol}) for cross-scope "
                "and critical changes.",
                "",
            ]
        )
    return "\n".join(lines).rstrip() + "\n"


def _section(lines: list[str], title: str, values: tuple[str, ...]) -> None:
    if not values:
        return
    lines.extend([f"## {title}", ""])
    lines.extend(f"- {value}" for value in values)
    lines.append("")


def _proof(invariant: Invariant) -> str:
    if invariant.verification == "command":
        return f"Verify with `{invariant.enforced_by}`."
    if invariant.verification == "manual":
        return f"Evidence: `{invariant.evidence_file}` contains `{invariant.anchor}`."
    return "Verification is currently unknown; treat this as declared debt."


def compile_manifest(manifest: Manifest) -> list[str]:
    outputs = render_outputs(manifest)
    lock = read_lock(manifest.root)
    expected = set(outputs)
    if lock:
        orphaned = sorted(set(lock.generated) - expected)
        if orphaned:
            joined = ", ".join(orphaned)
            raise KodamaError(
                f"lockfile owns maps no longer declared: {joined}; remove them explicitly"
            )

    targets: list[tuple[Path, str, str]] = []
    for relative, content in outputs.items():
        target = repo_path(manifest.root, relative, field="scopes[].map")
        if target.exists():
            if lock is None or relative not in lock.generated:
                raise KodamaError(f"refusing to overwrite unmanaged file: {relative}")
            actual = sha256_bytes(target.read_bytes())
            if actual != lock.generated[relative]:
                raise KodamaError(f"refusing to overwrite modified generated file: {relative}")
        targets.append((target, relative, content))

    for target, _, content in targets:
        _atomic_write(target, content)
    manifest_bytes = manifest.manifest_path.read_bytes()
    _atomic_write(manifest.root / LOCK_PATH, render_lock(manifest_bytes, outputs))
    return sorted(outputs)


def _atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(content)
        os.replace(temporary, path)
    except BaseException:
        Path(temporary).unlink(missing_ok=True)
        raise
